//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dsm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_menu
    {
        public int menu_id { get; set; }
        public string menu_name { get; set; }
        public string alias { get; set; }
        public string url { get; set; }
        public string action { get; set; }
        public string method { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string icon { get; set; }
        public string tag { get; set; }
    }
}
