//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dsm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fmsEntities : DbContext
    {
        public fmsEntities()
            : base("name=fmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app_menu> app_menu { get; set; }
        public virtual DbSet<directory> directories { get; set; }
        public virtual DbSet<menu_access> menu_access { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_directory> user_directory { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<role_menu> role_menu { get; set; }
        public virtual DbSet<role> roles { get; set; }
    }
}
