//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dsm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_menu
    {
        public int id { get; set; }
        public string role_id { get; set; }
        public Nullable<int> menu_id { get; set; }
        public string menu_alias { get; set; }
        public string free_fld { get; set; }
    }
}
