//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dsm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_directory
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string user_name { get; set; }
        public string dir_id { get; set; }
        public string remarks { get; set; }
        public string active { get; set; }
    }
}
