//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dsm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string uid { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string deleted { get; set; }
        public string enable { get; set; }
        public string expired { get; set; }
        public Nullable<int> fail_try { get; set; }
        public string locked { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string password { get; set; }
        public string reset_password { get; set; }
        public string username { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string designation { get; set; }
        public string free_fld1 { get; set; }
        public string free_fld2 { get; set; }
    }
}
